Fix case when ILIKE encounters a value with spaces in it
cloudflare-extension/unconventional pull request #3
Opened 2024-04-17 21:39 UTC by brianzhou13

### Context:

We were getting an error when we were attempting to do an `ILIKE ash ketch` where the value half of the string has a space in it.

![Screenshot 2024-04-17 at 5 38 04 PM](https://github.com/cloudflare-extension/unconventional/assets/5092263/898fe218-8f94-45cc-bdf2-6e9ec6fc5fab)

This PR helps handle that case.

2024-04-19 13:03 UTC, DeanMauro requested changes

2024-04-19 13:03 UTC, DeanMauro commented on src/utils/db.utils.ts
> +      }
A fix has to be generic as we support all `SqlWhereOperator`s. Each of these is a valid test case:
`name = 'John Smith'`
`name NOT LIKE '% Smith'`
`name IS NOT NULL`
`name IN ('Adam','Bruce','Craig')`
`age = 30`

Also note the `buildFilter` method. All string values should be surrounded by single quotes and all arrays surrounded by parentheses.

2024-05-20 15:31 UTC, closed without merging

2024-05-20 16:30 UTC, brianzhou13 commented
agh -- sorry, haven't had time to revisit this. will give it another stab in the future.

2024-05-20 19:59 UTC, maxduu commented
We're good @brianzhou13 with this PR: https://github.com/cloudflare-extension/unconventional/pull/4